coverage:
  status:
    project:
      default:
        # Only fail PR, if overall project codecov drops by 0.5%.
        threshold: 0.5%
        base: auto

    patch:
      default:
        # New code, should have 80% code coverage.
        target: 80%
