# The config of the 2s10x10-3p-3f scenario with the VectorObserver set as default
name: LevelBasedForaging
task_name: 2s-10x10-3p-3f

task_config:
  field_size: [10, 10]
  sight: 2
  players: 3
  max_num_food: 3
  max_player_level: 2
  force_coop: False
  max_episode_steps: 100
  min_player_level : 1
  min_food_level : null
  max_food_level : null

env_kwargs:
  {}  # there are no scenario specific env_kwargs for this env
