# The config of the tiny_4ag environment
name: RobotWarehouse
task_name: tiny-4ag

task_config:
  column_height: 8
  shelf_rows: 1
  shelf_columns: 3
  n_agents: 4
  sensor_range: 1
  request_queue_size: 4
  msg_bits : 0
  max_inactivity_steps : null
  max_steps : 500
  reward_type : 0

env_kwargs:
  {}  # there are no scenario specific env_kwargs for this env
