# The config of the 2s-8x8-2p-2f-coop scenario with the VectorObserver set as default.
name: LevelBasedForaging
task_name: 2s-8x8-2p-2f-coop

task_config:
  field_size: [8, 8] # size of the grid to generate.
  sight: 2 # field of view of an agent.
  players: 2 # number of agents on the grid.
  max_num_food: 2 # number of food in the environment.
  max_player_level: 2 # maximum level of the agents (inclusive).
  force_coop: True # force cooperation between agents.
  max_episode_steps: 100 # max number of steps per episode.
  min_player_level : 1 # minimum level of the agents (inclusive).
  min_food_level : null
  max_food_level : null

env_kwargs:
  {}  # there are no scenario specific env_kwargs for this env
