# The config of the 2s-8x8-2p-2f-coop scenario with the VectorObserver set as default.
name: MPE_simple_spread_v3
task_name: simple_spread_5ag

task_config:
  num_agents: 5
  num_landmarks: 5
  local_ratio: 0.5
  action_type: "Continuous" # "Continuous" or "Discrete"
