# --- Defaults FF-ISAC ---
seed: 1
n_envs: 16 # number of environments to run in parallel (vmapped)

# --- Agent observations ---
add_agent_id: True

# --- RL hyperparameters ---
# step related
total_timesteps: 3e8
explore_steps: 5000  # number of steps to take with random actions at the start of training
update_batch_size: 1 # number of vectorised gradient updates per device.

rollout_length: 1 # number of environment steps per vectorised environment.
epochs: 1 # number of learn epochs per training data batch.
policy_frequency: 4  # the frequency of training policy - every n q learning steps the policy is trained once

# sizes
buffer_size: 1000000  # size of the replay buffer. Note: total size is this * num_devices
batch_size: 64

# learning rates
policy_lr: 3e-4  # the learning rate of the policy network optimizer
q_lr: 1e-3  # the learning rate of the Q network network optimizer
alpha_lr: 13e-4  # the learning rate of the alpha optimizer

# SAC specific
tau: 0.005  # smoothing coefficient for target networks
gamma: 0.99  # discount factor

autotune: True  # whether to autotune alpha
target_entropy_scale: 5.0  # scale factor for target entropy (when auto-tuning)
init_alpha: 0.1  # initial entropy value when not using autotune
