defaults:
  - logger: rec_mappo
  - arch: anakin
  - system: ppo/rec_mappo
  - network: rnn  # [rnn, rcnn]
  - env: rware  # [cleaner, connector, gigastep, lbf, mabrax, matrax, rware, smax]
  - _self_
