defaults:
  - _self_
  - logger: logger
  - arch: anakin
  - system: sac/ff_masac
  - network: continuous_mlp  # [continuous_mlp]
  - env: mabrax  # [mabrax, mpe]

hydra:
  searchpath:
    - file://mava/configs
