# --- Defaults ---

# --- Experiment params ---
defaults:
  - _self_
  - rware_scenario: tiny-4ag-easy

# --- Environment ---
ENV_NAME: RobotWarehouse-v0

NUM_ENVS: 16  # Parallel updates / environments
NUM_UPDATES: 10 # Number of updates
SEED: 420

# --- RL hyperparameters ---
LR: 2.5e-4
UPDATE_BATCH_SIZE: 2
ROLLOUT_LENGTH: 16

PPO_EPOCHS: 4
NUM_MINIBATCHES: 2
GAMMA: 0.99
GAE_LAMBDA: 0.95
CLIP_EPS: 0.2
ENT_COEF: 0.01
VF_COEF: 0.5
MAX_GRAD_NORM: 0.5

# --- Evaluation ---
NUM_EVAL_EPISODES: 32
NUM_EVALUATION: 2
EVALUATION_GREEDY: False
ABSOLUTE_METRIC: True

# --- Logging options ---
USE_TF: true
USE_SACRED: true
