# ---Environment Configs---
defaults:
  - _self_
  - scenario: clean-10x10x3a # [con-10x10x3a, con-7x7x5a, con-10x10x5a, con-15x15x10a]
# Further environment config details in "clean-10x10x3a" file.

env_name: Cleaner # Used for logging purposes.

# Defines the metric that will be used to evaluate the performance of the agent.
# This metric is returned at the end of an experiment and can be used for hyperparameter tuning.
eval_metric: episode_return

kwargs:
  time_limit: 100
