# ---Environment Configs---
defaults:
  - _self_
  - scenario: hide_and_seek_5_vs_5 # [hide_and_seek_5_vs_5, identical_5_vs_5, waypoint_5_vs_5]

env_name: Gigastep

eval_metric: win_rate

kwargs:
  max_episode_length: 500 #equivalent to time_limit
  discrete_actions : True
  obs_type : vector # options: rgb, vector, rgb_vector)
