# ---Environment Configs---
defaults:
  - _self_
  - lbf_scenario: Foraging-2s-8x8-2p-2f-coop # [Foraging-2s-8x8-2p-2f-coop, Foraging-8x8-2p-2f-coop, Foraging-2s-10x10-3p-3f, Foraging-10x10-3p-3f, Foraging-15x15-4p-3f, Foraging-15x15-4p-5f]

env_name: LevelBasedForaging-v0
task_name: Foraging-2s-8x8-2p-2f-coop
