# ---Environment Configs---
defaults:
  - _self_

env_name: LevelBasedForaging  # Used for logging purposes.
scenario:
  name: lbforaging
  task_name: Foraging-8x8-2p-1f-v3

# Defines the metric that will be used to evaluate the performance of the agent.
# This metric is returned at the end of an experiment and can be used for hyperparameter tuning.
eval_metric: episode_return

# Whether the add agents IDs to the observations returned by the environment.
add_agent_id: False

# Whether or not to log the winrate of this environment.
log_win_rate: False

# Weather or not to sum the returned rewards over all of the agents.
use_shared_rewards: True
