# ---Environment Configs---
defaults:
  - _self_

env_name: Matrax

scenario:
  task_name: Climbing-stateless-v0

eval_metric: episode_return

# Possible scenarios:
#   1. Penalty-{k}-{state}-v0
#       1.1. k = {0, 25, 50, 75, 100}
#       1.2. state = {stateful, stateless}
#   2. Climbing-{state}-v0
#       2.1. state = {stateful, stateless}
#   3. NoConflict-{id}-{state}-v0
#       3.1. id = {1, 2, 3, ..., 20, 21}
#       3.2. state = {stateful, stateless}
#   4. Conflict-{id}-{state}-v0
#       4.1. id = {1, 2, 3, ..., 56, 57}
#       4.2. state = {stateful, stateless}

kwargs:
  time_limit: 500
