# --- Environment Configs---
defaults:
  - _self_
  - scenario: simple_spread_10ag # [simple_spread_3ag, simple_spread_5ag, simple_spread_10ag]

env_name: MPE  # Used for logging purposes and selection of the corresponding wrapper.

# Defines the metric that will be used to evaluate the performance of the agent.
# This metric is returned at the end of an experiment and can be used for hyperparameter tuning.
eval_metric: episode_return

# Whether the environment observations encode implicit agent IDs. If True, the AgentID wrapper is not used.
# Note: When using homogenisation_method = "max", a one-hot vector representing the agent ID is added.
# If the homogenisation method is changed, set this to False.
implicit_agent_id: True
# Whether or not to log the winrate of this environment. This should not be changed as not all
# environments have a winrate metric.
log_win_rate: False

kwargs:
  {}
