name: format_and_test

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    container: instadeepct/mava:jax-core-latest
    timeout-minutes: 45
    strategy:
      fail-fast: false
      matrix:
        docker-image: ["python:3.7", "python:3.8", "python:3.9"]
    steps:
      - name: Checkout mava
        uses: actions/checkout@v2
      - name: Check format and types
        run: |
          ./bash_scripts/check_format.sh
      - name: Run tests in docker
        run: |
          ./bash_scripts/tests.sh
      - name: Code coverage
        uses: codecov/codecov-action@v3
        with:
          env_vars: OS,PYTHON
          fail_ci_if_error: true
          files: ./coverage.xml
          flags: unittests
