name: format_and_test

on:
  push:
    branches: [develop, feature/jax-systems]
  pull_request:
    branches: [develop, feature/jax-systems]

# TODO(Kale-ab) Specify mava container to run tests on.
jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    strategy:
      fail-fast: false
      matrix:
        docker-image: ["python:3.7","python:3.8","python:3.9"]
    steps:
    - name: Checkout mava
      uses: actions/checkout@v2
    - name: Check format and types
      run: |
        docker run --mount "type=bind,src=$(pwd),dst=/tmp/mava" \
            -w "/tmp/mava" --rm ${{ matrix.docker-image }} /bin/bash bash_scripts/check_format.sh
    # - name: Set code coverage env variable
    #   env:
    #     CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
      # run: |
      #   ci_env=`bash <(curl -s https://codecov.io/env)`
    - name: Run tests in docker
      # run: |
      #   docker run $ci_env -e CI=true --mount "type=bind,src=$(pwd),dst=/tmp/mava" \
      #       -w "/tmp/mava" --rm ${{ matrix.docker-image }} /bin/bash bash_scripts/tests.sh
      run: |
        docker run --mount "type=bind,src=$(pwd),dst=/tmp/mava" \
            -w "/tmp/mava" --rm ${{ matrix.docker-image }} /bin/bash bash_scripts/tests.sh

    - name: Upload reports to codecov
      env:
        CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
      run: |
       curl -Os https://uploader.codecov.io/latest/linux/codecov
       find . -iregex "codecov.*"
       chmod +x codecov
       ./codecov -t ${CODECOV_TOKEN}
