# --- Logging options ---

use_tf: True # Whether to use tensorboard logging.
base_exp_path: results # Base path for sacred logging.
system_name: ~

# --- Neptune logging ---
use_neptune: True

kwargs:
  neptune_project: Instadeep/Mava
  neptune_tag: [rware]
  name: None # Unique ID from logging.
